### ISSUE TITLE
Clicking Sign-in button throws an internal server error

### ISSUE THREAD

**Issue by Gimnath-Perera** [jellydn/next-app-starter#1303]
### Describe the bug

In the hosted demo URL clicking the sign-in button takes users to internal server error screen.
![image](https://github.com/jellydn/next-app-starter/assets/55834384/d3d3d497-2339-46ac-bcc7-bc1e88704f70)

### Reproduction

Go to https://next-app-starter.productsway.com and press sign-in button

### System Info

```Shell
-Web browser: Google Chrome
-OS: macOs
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jellydn** [comment]
Thanks @Gimnath-Perera Fixed now. I found that it's missing to run `prisma generate` on build.

<img width="1136" alt="image" src="https://github.com/jellydn/next-app-starter/assets/870029/49d9d0e2-71e3-4028-ad3f-56fbb97c3d0a">
